### ISSUE TITLE
Schematics for the breakout board?

### ISSUE THREAD

**Issue by TPolzer** [GitJer/XiaomiMiaoMiaoCe#2]
Hi! Thanks a lot for this repo.

README.md lists a pinout for the eink flex, I think I understand how the pins map, but it would be great if I could confirm my understanding by looking at the schematic.

Would it be possible for you to upload the schematics of your breakout board, too?

**Comment by GitJer** [comment]
The breakout board is just a simple mapping from the flex to 10 pins, in the attached picture the traces on the pcb show this.

![breakout_board](https://user-images.githubusercontent.com/21146803/122663887-f5de7680-d19d-11eb-8d0f-d8c1ffd00589.jpg)

**Comment by TPolzer** [comment]
Thanks!
